import 'package:internship_app/models/internship_model.dart';

class InternshipService {
  static List<InternshipModel> getMockInternships() {
    return const [
      InternshipModel(
        id: '1',
        title: 'Flutter Developer Intern',
        company: 'TechCorp',
        location: 'Remote',
        workType: 'Remote',
        duration: '3 months',
        stipend: '₹15,000',
        stipendValue: 15000,
        logo: 'TC',
        color: 0xFF3B82F6,
        tags: ['Flutter', 'Dart'],
        skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs'],
        perks: ['Certificate', 'Letter of Recommendation', 'Flexible Hours'],
        description:
            'Join our team as a Flutter Developer Intern and work on real-world mobile applications. You will collaborate with senior engineers to build and ship features for our product.',
        openings: 5,
        featured: true,
        paid: true,
      ),
      InternshipModel(
        id: '2',
        title: 'UI/UX Design Intern',
        company: 'DesignHub',
        location: 'Bangalore',
        workType: 'On-site',
        duration: '6 months',
        stipend: '₹12,000',
        stipendValue: 12000,
        logo: 'DH',
        color: 0xFF3B82F6,
        tags: ['Figma', 'Adobe XD'],
        skills: ['Figma', 'Adobe XD', 'Prototyping', 'User Research'],
        perks: ['Certificate', 'Mentorship', 'Portfolio Projects'],
        description:
            'Work with our design team to create beautiful, user-centric interfaces. You will conduct user research, create wireframes, and prototype solutions for our clients.',
        openings: 3,
        featured: false,
        paid: true,
      ),
      InternshipModel(
        id: '3',
        title: 'Backend Developer Intern',
        company: 'DataSoft',
        location: 'On-site',
        workType: 'On-site',
        duration: '4 months',
        stipend: '₹18,000',
        stipendValue: 18000,
        logo: 'DS',
        color: 0xFF3B82F6,
        tags: ['Node.js', 'MongoDB'],
        skills: ['Node.js', 'MongoDB', 'Express.js', 'Docker'],
        perks: ['Certificate', 'Pre-Placement Offer', 'Team Lunches'],
        description:
            'Build and maintain scalable backend services. You will work on RESTful APIs, database design, and cloud deployments as part of our engineering team.',
        openings: 2,
        featured: false,
        paid: true,
      ),
      InternshipModel(
        id: '4',
        title: 'Machine Learning Intern',
        company: 'AI Labs',
        location: 'Remote',
        workType: 'Remote',
        duration: '6 months',
        stipend: '₹20,000',
        stipendValue: 20000,
        logo: 'AL',
        color: 0xFF3B82F6,
        tags: ['Python', 'TensorFlow'],
        skills: ['Python', 'TensorFlow', 'PyTorch', 'Data Analysis'],
        perks: ['Certificate', 'Research Paper Co-authorship', 'Flexible Hours'],
        description:
            'Work on cutting-edge ML models for computer vision and NLP tasks. You will participate in model training, evaluation, and deployment pipelines.',
        openings: 4,
        featured: true,
        paid: true,
      ),
      InternshipModel(
        id: '5',
        title: 'Product Management Intern',
        company: 'StartupX',
        location: 'Hybrid',
        workType: 'Hybrid',
        duration: '3 months',
        stipend: 'Unpaid',
        stipendValue: 0,
        logo: 'SX',
        color: 0xFF3B82F6,
        tags: ['Agile', 'Jira'],
        skills: ['Agile', 'Jira', 'Product Roadmapping', 'User Stories'],
        perks: ['Certificate', 'Networking Events', 'Mentorship from Founders'],
        description:
            'Get hands-on experience in product lifecycle management. You will work directly with the founders to define product vision, prioritize features, and track KPIs.',
        openings: 1,
        featured: false,
        paid: false,
      ),
    ];
  }
}
