const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Skill =require('./schema/skillsSchema')// Assuming you have the Skill model defined

// Load environment variables
dotenv.config();

// Connect to MongoDB Atlas
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('Connected to MongoDB');
  } catch (error) {
    console.error('Error connecting to MongoDB:', error);
    process.exit(1); // Exit process if there's a connection error
  }
};

// List of skills to insert
const skills = [
  "3D Animation",
  "3D Modeling",
  "A/B Testing",
  "Accounting",
  "Adobe After Effects",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Adobe XD",
  "Advertising",
  "Agile Development",
  "Agile Methodology",
  "AI/ML",
  "AJAX",
  "Algorithms",
  "Alteryx",
  "Amazon EC2",
  "Amazon RDS",
  "Amazon S3",
  "Amazon SES",
  "Amazon SNS",
  "Amazon Web Services (AWS)",
  "Android Development",
  "Angular",
  "Animation",
  "Ansible",
  "Apache",
  "Apache Hadoop",
  "Apache Kafka",
  "Apache Spark",
  "API Development",
  "App Development",
  "Appium",
  "Arduino",
  "ASP.NET",
  "Augmented Reality (AR)",
  "AutoCAD",
  "Automation Testing",
  "Azure",
  "Backbone.js",
  "Backend Development",
  "Balsamiq",
  "Bash Scripting",
  "Big Data",
  "Bioinformatics",
  "Blockchain",
  "Blockchain Development",
  "Blogging",
  "Bootstrap",
  "Bootstrap 4",
  "Brand Management",
  "Business Analytics",
  "Business Development",
  "Business Intelligence",
  "Business Strategy",
  "C Programming",
  "C#",
  "C++",
  "CAD",
  "Canva",
  "Cassandra",
  "Chef",
  "Chatbot Development",
  "Cinematography",
  "Cloud Architecture",
  "Cloud Computing",
  "Cloud Infrastructure",
  "Cloud Services",
  "CNC Programming",
  "COBOL",
  "Cognitive Computing",
  "Communication",
  "Computer Vision",
  "Content Marketing",
  "Content Writing",
  "Continuous Integration",
  "Conversion Rate Optimization",
  "Cordova",
  "CorelDRAW",
  "CRM Software",
  "Cryptocurrency",
  "CSS",
  "CSS3",
  "Customer Relationship Management (CRM)",
  "Customer Support",
  "Cyber Forensics",
  "Cyber Law",
  "Cybersecurity",
  "Data Analytics",
  "Data Engineering",
  "Data Entry",
  "Data Integration",
  "Data Mining",
  "Data Modeling",
  "Data Science",
  "Data Structures",
  "Data Visualization",
  "Data Warehousing",
  "Database Design",
  "Database Management",
  "Deep Learning",
  "Deep Reinforcement Learning",
  "Design Patterns",
  "Design Thinking",
  "DevOps",
  "Django",
  "Django REST Framework",
  "DNS",
  "Docker",
  "Docker Swarm",
  "eCommerce Development",
  "E-commerce",
  "Edge Computing",
  "Editing",
  "Elasticsearch",
  "Electronic Design Automation",
  "Embedded C",
  "Embedded Systems",
  "Ember.js",
  "Enterprise Architecture",
  "Enterprise Resource Planning (ERP)",
  "Ethical Hacking",
  "Event Management",
  "Express.js",
  "Facebook Ads",
  "Facebook Marketing",
  "Figma",
  "Film Making",
  "Financial Analysis",
  "Firebase",
  "Firmware Development",
  "Flask",
  "Flutter",
  "Freelancing",
  "Frontend Development",
  "Full Stack Development",
  "Functional Programming",
  "Game Design",
  "Game Development",
  "Game Programming",
  "Git",
  "GitHub",
  "GitLab",
  "Go Programming Language",
  "Google Ads",
  "Google Analytics",
  "Graphic Design",
  "GraphQL",
  "Grunt",
  "Growth Hacking",
  "Gulp.js",
  "Hadoop",
  "Haskell",
  "Hibernate",
  "HTML",
  "HTML5",
  "IBM Cloud",
  "Illustration",
  "Image Processing",
  "Indesign",
  "Informatica",
  "Information Security",
  "Integrated Development Environment (IDE)",
  "Internet Security",
  "IoT (Internet of Things)",
  "InVision",
  "iOS Development",
  "Ionic Framework",
  "J2EE",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jenkins Pipeline",
  "JIRA",
  "JMeter",
  "Joomla",
  "jQuery",
  "JSON",
  "JSP",
  "JUnit",
  "Kafka",
  "Kafka Streams",
  "Kibana",
  "Kotlin",
  "Kotlin Multiplatform",
  "Kubernetes",
  "Kubernetes Clusters",
  "LabVIEW",
  "Lambda Functions",
  "LAMP Stack",
  "Laravel",
  "Leadership",
  "Leadership Development",
  "LESS",
  "LinkedIn Marketing",
  "Linux",
  "Load Balancing",
  "Logistics",
  "Lua",
  "Machine Learning",
  "Machine Vision",
  "Magento",
  "Market Research",
  "Marketing",
  "MATLAB",
  "Maya",
  "Mean Stack",
  "MERN Stack",
  "Microcontrollers",
  "Microservices",
  "Mobile App Design",
  "Mobile App Testing",
  "MongoDB",
  "Motion Graphics",
  "Moodle",
  "MySQL",
  "Natural Language Processing (NLP)",
  "NestJS",
  "Networking",
  "Neural Networks",
  "Nginx",
  "Node.js",
  "NoSQL",
  "Objective-C",
  "Objective-Oriented Design",
  "OAuth",
  "OOP (Object-Oriented Programming)",
  "OpenCV",
  "OpenGL",
  "OpenStack",
  "Operating Systems",
  "Oracle",
  "Pandas",
  "Penetration Testing",
  "Pentaho",
  "Perl",
  "Photography",
  "Photoshop",
  "PHP",
  "PostgreSQL",
  "Power BI",
  "PowerPoint",
  "Predictive Analytics",
  "Premiere",
  "Premiere Pro",
  "PRINCE2",
  "Problem Solving",
  "Product Design",
  "Product Management",
  "Programming",
  "Project Management",
  "Prototyping",
  "Public Speaking",
  "Puppet",
  "Python",
  "Quantum Computing",
  "R Programming",
  "RabbitMQ",
  "Raspberry Pi",
  "React",
  "React Native",
  "React.js",
  "Redis",
  "Redux",
  "Reinforcement Learning",
  "REST APIs",
  "RESTful Web Services",
  "Robotics",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Sales",
  "Salesforce",
  "SASS",
  "Search Engine Optimization (SEO)",
  "Selenium",
  "Shell Scripting",
  "Shopify",
  "Sketch",
  "Slack API",
  "Smart Contracts",
  "Snowflake",
  "Social Media Marketing",
  "Software Development",
  "Software Testing",
  "Solidity",
  "Spring Boot",
  "SQL",
  "SQL Server",
  "SQLite",
  "Stakeholder Management",
  "Statistical Analysis",
  "Storyboarding",
  "Strategic Planning",
  "Stripe API",
  "Swift",
  "Symfony",
  "System Administration",
  "System Design",
  "Tableau",
  "Technical Writing",
  "TensorFlow",
  "Terraform",
  "Trello",
  "TypeORM",
  "TypeScript",
  "UI/UX Design",
  "Unity",
  "Unity 3D",
  "Unreal Engine",
  "User Research",
  "UX Research",
  "Vagrant",
  "Video Editing",
  "Video Production",
  "Virtual Machines",
  "Virtual Reality (VR)",
  "Vim",
  "VMware",
  "Vue.js",
  "Web Design",
  "Web Development",
  "Webpack",
  "Wireshark",
  "Windows Server",
  "WordPress",
  "Wix",
  "XML",
  "XML Parsing",
  "XSLT",
  "Xamarin",
  "YouTube Marketing",
  "YouTube SEO",
  "Zeplin",
  "ZigBee",
  "ZBrush",
  "Zoho CRM",
  "Zookeeper"
];



// Function to insert skills into MongoDB
const insertSkills = async () => {
  try {
    await Skill.insertMany(
      skills.map(skill => ({ name: skill })) // Mapping the skill names to the schema
    );
    console.log('Skills inserted successfully');
    mongoose.disconnect(); // Close the connection after insertion
  } catch (error) {
    console.error('Error inserting skills:', error);
  }
};

// Execute the script
const run = async () => {
  await connectDB();
  await insertSkills();
};

run();
