const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Profile =require('./schema/profileSchema')

// Load environment variables
dotenv.config();

// Connect to MongoDB Atlas
const connectDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('Connected to MongoDB');
  } catch (error) {
    console.error('Error connecting to MongoDB:', error);
    process.exit(1); // Exit process if there's a connection error
  }
};

// List of skills to insert
const jobProfiles = [
  "3D Animation",
  "Account Management",
  "Accounting & Auditing",
  "Acting/Performing Arts",
  "Administrative Assistant",
  "Advertising Specialist",
  "Aerospace Engineering",
  "AI (Artificial Intelligence)",
  "Android Development",
  "Animation Design",
  "App Developer",
  "Application Support Engineer",
  "Architecture",
  "Art Director",
  "Asset Management",
  "Assistant Producer",
  "Audio Engineer",
  "Automation Engineer",
  "Automotive Engineering",
  "AWS Development",
  "Back-End Development",
  "Bank Teller",
  "Banking Operations",
  "Big Data Engineer",
  "Bioinformatics Researcher",
  "Biomedical Engineering",
  "Blockchain Development",
  "Brand Management",
  "Broadcast Engineering",
  "Budget Analyst",
  "Building Inspector",
  "Business Analyst",
  "Business Consultant",
  "Business Development",
  "Business Intelligence Analyst",
  "Call Center Agent",
  "Cartography",
  "Chemical Engineering",
  "Civil Engineering",
  "Claims Adjuster",
  "Cloud Architect",
  "Cloud Computing",
  "Cloud Security Engineer",
  "Communications Specialist",
  "Compliance Officer",
  "Computer Hardware Engineer",
  "Construction Manager",
  "Content Creation",
  "Content Editor",
  "Content Management",
  "Content Marketing",
  "Content Strategist",
  "Content Writing",
  "Corporate Law Intern",
  "Corporate Trainer",
  "Cost Estimator",
  "Creative Director",
  "CRM Development",
  "Customer Success Manager",
  "Cybersecurity",
  "Data Analytics",
  "Data Architect",
  "Data Engineering",
  "Data Entry Clerk",
  "Data Governance Specialist",
  "Data Quality Analyst",
  "Data Science",
  "Database Administration",
  "Debt Collection Officer",
  "Dental Assistant",
  "Dentist",
  "Design Engineer",
  "Desktop Support Technician",
  "DevOps Engineer",
  "Digital Illustrator",
  "Digital Marketing",
  "Digital Product Designer",
  "E-Commerce Management",
  "Electrical Engineering",
  "Elementary School Teacher",
  "Embedded Systems Development",
  "Environmental Engineer",
  "ERP Development",
  "Event Coordination",
  "Event Management",
  "Exhibition Designer",
  "Fashion Design",
  "Fashion Marketing",
  "Fashion Stylist",
  "Film Director",
  "Film Editor",
  "FinTech Development",
  "Financial Analyst",
  "Financial Planner",
  "Fitness Trainer",
  "Flutter Development",
  "Food Technology",
  "Forensic Scientist",
  "Front-End Development",
  "Full-Stack Development",
  "Fundraising Coordinator",
  "Game Design",
  "Game Development",
  "General Practitioner (Doctor)",
  "Genetic Counselor",
  "Geologist",
  "Graphic Design",
  "Green Energy Consultant",
  "Hair Stylist",
  "Hardware Development",
  "Healthcare Administration",
  "Healthcare Management",
  "Hotel Management",
  "HR Business Partner",
  "HR Generalist",
  "HR Management",
  "HVAC Engineer",
  "Illustrator",
  "Industrial Designer",
  "Industrial Engineering",
  "Information Security Analyst",
  "Information Systems Manager",
  "Interior Design",
  "International Trade Specialist",
  "Investment Banking",
  "IT Consultant",
  "IT Security Specialist",
  "IT Support",
  "IT Systems Administrator",
  "Java Development",
  "Journalism",
  "Lab Technician",
  "Language Translation",
  "Law/Legal Intern",
  "Litigation Assistant",
  "Logistics Coordinator",
  "Machine Learning Engineer",
  "Maintenance Engineer",
  "Manufacturing Engineering",
  "Marine Biologist",
  "Market Research",
  "Marketing Analyst",
  "Marketing Manager",
  "Materials Engineer",
  "Mechanical Engineering",
  "Medical Assistant",
  "Medical Coding",
  "Medical Equipment Technician",
  "Medical Laboratory Scientist",
  "Medical Research",
  "Microbiologist",
  "Mobile App Development (Android)",
  "Mobile App Development (iOS)",
  "Motion Graphics Design",
  "Museum Curator",
  "Music Producer",
  "Network Administrator",
  "Network Engineer",
  "Nutritionist/Dietician",
  "Occupational Therapist",
  "Office Administrator",
  "Oil and Gas Engineer",
  "Operations Analyst",
  "Operations Management",
  "Packaging Design",
  "Paralegal",
  "Patent Analyst",
  "Payroll Specialist",
  "Performance Marketing Specialist",
  "Personal Assistant",
  "Petroleum Engineer",
  "Pharmacist",
  "Photographer",
  "PHP Development",
  "Physical Therapist",
  "Physiotherapist",
  "Pilates Instructor",
  "Policy Analyst",
  "Political Campaign Manager",
  "Portfolio Manager",
  "PR (Public Relations) Specialist",
  "Private Equity Analyst",
  "Product Design",
  "Product Management",
  "Production Assistant",
  "Production Engineer",
  "Project Management",
  "Property Manager",
  "Python Development",
  "Quality Assurance (QA)",
  "Quality Control Analyst",
  "React Native Development",
  "Real Estate Development",
  "Recruiter",
  "Renewable Energy Engineer",
  "Research Analyst",
  "Respiratory Therapist",
  "Restaurant Manager",
  "Risk Management Analyst",
  "Ruby on Rails Development",
  "Travels",
  "Tourism",
  "Web Development",
];



// Function to insert skills into MongoDB
const insertProfiles = async () => {
  try {
    await Profile.insertMany(
      jobProfiles.map(profile => ({ name: profile })) // Mapping the skill names to the schema
    );
    console.log('profiles inserted successfully');
    mongoose.disconnect(); // Close the connection after insertion
  } catch (error) {
    console.error('Error inserting profile:', error);
  }
};

// Execute the script
const run = async () => {
  await connectDB();
  await insertProfiles();
};

run();
